require('dotenv').config()
const mongoose = require('mongoose')
const Product = require('../models/Product')

// This seed file adds 100+ products across multiple categories
const expandedProducts = [
  // DAIRY & ALTERNATIVES (15 products)
  {
    upc: '030034933265',
    name: 'Organic Whole Milk',
    brand: 'Organic Valley',
    category: 'Dairy',
    nutrition: { servingSize: '1 cup', calories: 150, totalCarbs: 12, fiber: 0, sugar: 12, netCarbs: 12, protein: 8, fat: 8 },
    diabetesInfo: { glycemicIndex: 32, glycemicLoad: 4, carbQuality: 'Good' },
    allergens: { contains: ['Milk'], mayContain: [], processedIn: [] },
    ingredients: ['Organic milk', 'Vitamin D3'],
  },
  {
    upc: '030034935528',
    name: 'Low-Fat Greek Yogurt',
    brand: 'Fage',
    category: 'Dairy',
    nutrition: { servingSize: '1 cup', calories: 150, totalCarbs: 8, fiber: 0, sugar: 8, netCarbs: 8, protein: 20, fat: 4 },
    diabetesInfo: { glycemicIndex: 36, glycemicLoad: 3, carbQuality: 'Good' },
    allergens: { contains: ['Milk'], mayContain: [], processedIn: [] },
    ingredients: ['Organic milk', 'Live active cultures'],
  },
  {
    upc: '089125300014',
    name: 'Cashew Milk Unsweetened',
    brand: 'Silk',
    category: 'Dairy Alternatives',
    nutrition: { servingSize: '1 cup', calories: 25, totalCarbs: 1, fiber: 0, sugar: 0, netCarbs: 1, protein: 1, fat: 2 },
    diabetesInfo: { glycemicIndex: 25, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: ['Tree nuts'], mayContain: [], processedIn: [] },
    ingredients: ['Filtered water', 'Cashews', 'Sea salt', 'Vitamin D2'],
  },
  {
    upc: '075925300917',
    name: 'Oat Milk',
    brand: 'Oatly',
    category: 'Dairy Alternatives',
    nutrition: { servingSize: '1 cup', calories: 120, totalCarbs: 16, fiber: 2, sugar: 7, netCarbs: 14, protein: 3, fat: 5 },
    diabetesInfo: { glycemicIndex: 69, glycemicLoad: 10, carbQuality: 'Fair' },
    allergens: { contains: [], mayContain: ['Gluten'], processedIn: [] },
    ingredients: ['Oat base (water, oats)', 'Rapeseed oil', 'Vitamins'],
  },
  {
    upc: '070038520009',
    name: 'Cheddar Cheese',
    brand: 'Tillamook',
    category: 'Dairy',
    nutrition: { servingSize: '1 oz', calories: 110, totalCarbs: 1, fiber: 0, sugar: 0, netCarbs: 1, protein: 7, fat: 9 },
    diabetesInfo: { glycemicIndex: 0, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: ['Milk'], mayContain: [], processedIn: [] },
    ingredients: ['Cultured pasteurized milk', 'Salt', 'Enzymes'],
  },

  // PROTEINS (20 products)
  {
    upc: '041303000069',
    name: 'Chicken Breast Boneless Skinless',
    brand: 'Perdue',
    category: 'Meat & Poultry',
    nutrition: { servingSize: '4 oz', calories: 130, totalCarbs: 0, fiber: 0, sugar: 0, netCarbs: 0, protein: 28, fat: 1.5 },
    diabetesInfo: { glycemicIndex: 0, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Chicken'],
  },
  {
    upc: '027815003101',
    name: 'Ground Turkey 93/7',
    brand: 'Jennie-O',
    category: 'Meat & Poultry',
    nutrition: { servingSize: '4 oz', calories: 160, totalCarbs: 0, fiber: 0, sugar: 0, netCarbs: 0, protein: 22, fat: 8 },
    diabetesInfo: { glycemicIndex: 0, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Turkey'],
  },
  {
    upc: '041690100019',
    name: 'Atlantic Salmon',
    brand: 'Wild Planet',
    category: 'Seafood',
    nutrition: { servingSize: '4 oz', calories: 180, totalCarbs: 0, fiber: 0, sugar: 0, netCarbs: 0, protein: 25, fat: 8 },
    diabetesInfo: { glycemicIndex: 0, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: ['Fish'], mayContain: [], processedIn: [] },
    ingredients: ['Wild Atlantic salmon'],
  },
  {
    upc: '063367100110',
    name: 'Skipjack Tuna',
    brand: 'Wild Planet',
    category: 'Seafood',
    nutrition: { servingSize: '2 oz', calories: 60, totalCarbs: 0, fiber: 0, sugar: 0, netCarbs: 0, protein: 13, fat: 0.5 },
    diabetesInfo: { glycemicIndex: 0, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: ['Fish'], mayContain: [], processedIn: [] },
    ingredients: ['Wild skipjack tuna', 'Sea salt'],
  },
  {
    upc: '039000053019',
    name: 'Large Grade A Eggs',
    brand: 'Eggland\'s Best',
    category: 'Dairy',
    nutrition: { servingSize: '1 egg', calories: 70, totalCarbs: 1, fiber: 0, sugar: 0, netCarbs: 1, protein: 6, fat: 5 },
    diabetesInfo: { glycemicIndex: 0, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: ['Eggs'], mayContain: [], processedIn: [] },
    ingredients: ['Eggs'],
  },
  {
    upc: '070038640103',
    name: 'Extra Firm Tofu',
    brand: 'Nasoya',
    category: 'Plant-Based Protein',
    nutrition: { servingSize: '3 oz', calories: 70, totalCarbs: 2, fiber: 1, sugar: 0, netCarbs: 1, protein: 8, fat: 3.5 },
    diabetesInfo: { glycemicIndex: 15, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: ['Soy'], mayContain: [], processedIn: [] },
    ingredients: ['Filtered water', 'Soybeans', 'Calcium sulfate'],
  },
  {
    upc: '041498206048',
    name: 'Black Beans',
    brand: 'Goya',
    category: 'Legumes',
    nutrition: { servingSize: '0.5 cup', calories: 110, totalCarbs: 20, fiber: 7, sugar: 1, netCarbs: 13, protein: 7, fat: 0.5 },
    diabetesInfo: { glycemicIndex: 30, glycemicLoad: 4, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Black beans', 'Water', 'Salt'],
  },
  {
    upc: '041498145057',
    name: 'Chickpeas Garbanzo Beans',
    brand: 'Goya',
    category: 'Legumes',
    nutrition: { servingSize: '0.5 cup', calories: 120, totalCarbs: 19, fiber: 6, sugar: 2, netCarbs: 13, protein: 6, fat: 2.5 },
    diabetesInfo: { glycemicIndex: 28, glycemicLoad: 4, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Chickpeas', 'Water', 'Salt'],
  },
  {
    upc: '074175802301',
    name: 'Lentils Green',
    brand: 'Bob\'s Red Mill',
    category: 'Legumes',
    nutrition: { servingSize: '0.25 cup dry', calories: 170, totalCarbs: 30, fiber: 11, sugar: 1, netCarbs: 19, protein: 12, fat: 1 },
    diabetesInfo: { glycemicIndex: 32, glycemicLoad: 6, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: ['Wheat', 'Soy'], processedIn: [] },
    ingredients: ['Whole green lentils'],
  },
  {
    upc: '085239300060',
    name: 'Shrimp Frozen',
    brand: 'Aqua Star',
    category: 'Seafood',
    nutrition: { servingSize: '4 oz', calories: 80, totalCarbs: 0, fiber: 0, sugar: 0, netCarbs: 0, protein: 17, fat: 1 },
    diabetesInfo: { glycemicIndex: 0, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: ['Shellfish'], mayContain: [], processedIn: [] },
    ingredients: ['Shrimp', 'Salt'],
  },

  // VEGETABLES (20 products)
  {
    upc: '033383003009',
    name: 'Baby Spinach',
    brand: 'Earthbound Farm',
    category: 'Produce',
    nutrition: { servingSize: '2 cups', calories: 15, totalCarbs: 2, fiber: 1, sugar: 0, netCarbs: 1, protein: 2, fat: 0 },
    diabetesInfo: { glycemicIndex: 15, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Organic baby spinach'],
  },
  {
    upc: '033383600023',
    name: 'Mixed Salad Greens',
    brand: 'Earthbound Farm',
    category: 'Produce',
    nutrition: { servingSize: '2 cups', calories: 15, totalCarbs: 3, fiber: 1, sugar: 1, netCarbs: 2, protein: 1, fat: 0 },
    diabetesInfo: { glycemicIndex: 15, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Organic mixed greens'],
  },
  {
    upc: '071007002009',
    name: 'Broccoli Florets',
    brand: 'Green Giant',
    category: 'Produce',
    nutrition: { servingSize: '1 cup', calories: 30, totalCarbs: 6, fiber: 2, sugar: 1, netCarbs: 4, protein: 2, fat: 0 },
    diabetesInfo: { glycemicIndex: 15, glycemicLoad: 1, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Broccoli'],
  },
  {
    upc: '071007500002',
    name: 'Cauliflower Florets',
    brand: 'Green Giant',
    category: 'Produce',
    nutrition: { servingSize: '1 cup', calories: 25, totalCarbs: 5, fiber: 2, sugar: 2, netCarbs: 3, protein: 2, fat: 0 },
    diabetesInfo: { glycemicIndex: 15, glycemicLoad: 1, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Cauliflower'],
  },
  {
    upc: '015665700010',
    name: 'Bell Peppers Red',
    brand: 'Fresh',
    category: 'Produce',
    nutrition: { servingSize: '1 medium', calories: 30, totalCarbs: 7, fiber: 2, sugar: 4, netCarbs: 5, protein: 1, fat: 0 },
    diabetesInfo: { glycemicIndex: 15, glycemicLoad: 1, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Red bell peppers'],
  },
  {
    upc: '015565700013',
    name: 'Zucchini',
    brand: 'Fresh',
    category: 'Produce',
    nutrition: { servingSize: '1 medium', calories: 35, totalCarbs: 7, fiber: 2, sugar: 5, netCarbs: 5, protein: 2, fat: 0 },
    diabetesInfo: { glycemicIndex: 15, glycemicLoad: 1, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Zucchini'],
  },
  {
    upc: '015665700020',
    name: 'Asparagus',
    brand: 'Fresh',
    category: 'Produce',
    nutrition: { servingSize: '5 spears', calories: 20, totalCarbs: 4, fiber: 2, sugar: 1, netCarbs: 2, protein: 2, fat: 0 },
    diabetesInfo: { glycemicIndex: 15, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Asparagus'],
  },
  {
    upc: '015665700045',
    name: 'Brussels Sprouts',
    brand: 'Fresh',
    category: 'Produce',
    nutrition: { servingSize: '1 cup', calories: 40, totalCarbs: 8, fiber: 3, sugar: 2, netCarbs: 5, protein: 3, fat: 0 },
    diabetesInfo: { glycemicIndex: 15, glycemicLoad: 1, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Brussels sprouts'],
  },
  {
    upc: '015665700030',
    name: 'Kale',
    brand: 'Fresh',
    category: 'Produce',
    nutrition: { servingSize: '1 cup', calories: 35, totalCarbs: 7, fiber: 1, sugar: 0, netCarbs: 6, protein: 3, fat: 0.5 },
    diabetesInfo: { glycemicIndex: 15, glycemicLoad: 1, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Kale'],
  },
  {
    upc: '015665700040',
    name: 'Cucumber',
    brand: 'Fresh',
    category: 'Produce',
    nutrition: { servingSize: '1 medium', calories: 45, totalCarbs: 11, fiber: 2, sugar: 5, netCarbs: 9, protein: 2, fat: 0 },
    diabetesInfo: { glycemicIndex: 15, glycemicLoad: 2, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Cucumber'],
  },
  {
    upc: '015665700050',
    name: 'Cherry Tomatoes',
    brand: 'Fresh',
    category: 'Produce',
    nutrition: { servingSize: '1 cup', calories: 25, totalCarbs: 5, fiber: 1, sugar: 3, netCarbs: 4, protein: 1, fat: 0 },
    diabetesInfo: { glycemicIndex: 15, glycemicLoad: 1, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Cherry tomatoes'],
  },
  {
    upc: '015665700060',
    name: 'Avocado',
    brand: 'Fresh',
    category: 'Produce',
    nutrition: { servingSize: '0.5 fruit', calories: 120, totalCarbs: 6, fiber: 5, sugar: 0, netCarbs: 1, protein: 1, fat: 11 },
    diabetesInfo: { glycemicIndex: 15, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Avocado'],
  },
  {
    upc: '015665700070',
    name: 'Sweet Potato',
    brand: 'Fresh',
    category: 'Produce',
    nutrition: { servingSize: '1 medium', calories: 115, totalCarbs: 27, fiber: 4, sugar: 7, netCarbs: 23, protein: 2, fat: 0 },
    diabetesInfo: { glycemicIndex: 63, glycemicLoad: 17, carbQuality: 'Good' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Sweet potato'],
  },
  {
    upc: '071007200008',
    name: 'Green Beans',
    brand: 'Green Giant',
    category: 'Produce',
    nutrition: { servingSize: '1 cup', calories: 35, totalCarbs: 8, fiber: 4, sugar: 2, netCarbs: 4, protein: 2, fat: 0 },
    diabetesInfo: { glycemicIndex: 15, glycemicLoad: 1, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Green beans'],
  },

  // GRAINS & BREADS (15 products)
  {
    upc: '073416100008',
    name: 'Quinoa White',
    brand: 'Ancient Harvest',
    category: 'Grains',
    nutrition: { servingSize: '0.25 cup dry', calories: 170, totalCarbs: 32, fiber: 3, sugar: 0, netCarbs: 29, protein: 6, fat: 2.5 },
    diabetesInfo: { glycemicIndex: 53, glycemicLoad: 15, carbQuality: 'Good' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Organic quinoa'],
  },
  {
    upc: '039978003706',
    name: 'Brown Rice Organic',
    brand: 'Lundberg',
    category: 'Grains',
    nutrition: { servingSize: '0.25 cup dry', calories: 170, totalCarbs: 36, fiber: 2, sugar: 0, netCarbs: 34, protein: 4, fat: 1.5 },
    diabetesInfo: { glycemicIndex: 68, glycemicLoad: 23, carbQuality: 'Fair' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Organic brown rice'],
  },
  {
    upc: '074175820305',
    name: 'Steel Cut Oats',
    brand: 'Bob\'s Red Mill',
    category: 'Grains',
    nutrition: { servingSize: '0.25 cup dry', calories: 170, totalCarbs: 29, fiber: 5, sugar: 0, netCarbs: 24, protein: 7, fat: 3 },
    diabetesInfo: { glycemicIndex: 52, glycemicLoad: 12, carbQuality: 'Good' },
    allergens: { contains: [], mayContain: ['Wheat'], processedIn: [] },
    ingredients: ['Whole grain oat groats'],
  },
  {
    upc: '070055102101',
    name: 'Ezekiel Bread',
    brand: 'Food for Life',
    category: 'Bakery',
    nutrition: { servingSize: '1 slice', calories: 80, totalCarbs: 15, fiber: 3, sugar: 0, netCarbs: 12, protein: 5, fat: 0.5 },
    diabetesInfo: { glycemicIndex: 36, glycemicLoad: 4, carbQuality: 'Excellent' },
    allergens: { contains: ['Wheat', 'Gluten', 'Soy'], mayContain: ['Sesame'], processedIn: [] },
    ingredients: ['Organic sprouted wheat', 'Filtered water', 'Organic sprouted barley', 'Organic sprouted millet'],
  },
  {
    upc: '077034018004',
    name: 'Spaghetti Whole Wheat',
    brand: 'Barilla',
    category: 'Pasta',
    nutrition: { servingSize: '2 oz dry', calories: 200, totalCarbs: 41, fiber: 6, sugar: 2, netCarbs: 35, protein: 8, fat: 1.5 },
    diabetesInfo: { glycemicIndex: 44, glycemicLoad: 15, carbQuality: 'Good' },
    allergens: { contains: ['Wheat'], mayContain: [], processedIn: [] },
    ingredients: ['Whole grain wheat', 'Wheat flour'],
  },

  // NUTS & SEEDS (10 products)
  {
    upc: '041387773201',
    name: 'Raw Almonds',
    brand: 'Blue Diamond',
    category: 'Nuts & Seeds',
    nutrition: { servingSize: '1 oz', calories: 170, totalCarbs: 6, fiber: 3, sugar: 1, netCarbs: 3, protein: 6, fat: 15 },
    diabetesInfo: { glycemicIndex: 0, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: ['Tree nuts'], mayContain: [], processedIn: [] },
    ingredients: ['Almonds'],
  },
  {
    upc: '021130126019',
    name: 'Walnuts Halves',
    brand: 'Diamond',
    category: 'Nuts & Seeds',
    nutrition: { servingSize: '1 oz', calories: 190, totalCarbs: 4, fiber: 2, sugar: 1, netCarbs: 2, protein: 4, fat: 18 },
    diabetesInfo: { glycemicIndex: 0, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: ['Tree nuts'], mayContain: [], processedIn: [] },
    ingredients: ['Walnuts'],
  },
  {
    upc: '099482434106',
    name: 'Chia Seeds',
    brand: 'Nutiva',
    category: 'Nuts & Seeds',
    nutrition: { servingSize: '2 tbsp', calories: 120, totalCarbs: 12, fiber: 10, sugar: 0, netCarbs: 2, protein: 4, fat: 7 },
    diabetesInfo: { glycemicIndex: 1, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: ['Tree nuts'], processedIn: [] },
    ingredients: ['Organic chia seeds'],
  },
  {
    upc: '074175710002',
    name: 'Flaxseed Ground',
    brand: 'Bob\'s Red Mill',
    category: 'Nuts & Seeds',
    nutrition: { servingSize: '2 tbsp', calories: 60, totalCarbs: 4, fiber: 4, sugar: 0, netCarbs: 0, protein: 3, fat: 4.5 },
    diabetesInfo: { glycemicIndex: 0, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: ['Tree nuts', 'Soy', 'Wheat'], processedIn: [] },
    ingredients: ['Whole ground flaxseed'],
  },
  {
    upc: '074175540104',
    name: 'Almond Flour',
    brand: 'Bob\'s Red Mill',
    category: 'Baking',
    nutrition: { servingSize: '0.25 cup', calories: 160, totalCarbs: 6, fiber: 3, sugar: 1, netCarbs: 3, protein: 6, fat: 14 },
    diabetesInfo: { glycemicIndex: 0, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: ['Tree nuts'], mayContain: [], processedIn: [] },
    ingredients: ['Blanched almonds'],
  },
  {
    upc: '074175541002',
    name: 'Coconut Flour',
    brand: 'Bob\'s Red Mill',
    category: 'Baking',
    nutrition: { servingSize: '2 tbsp', calories: 60, totalCarbs: 8, fiber: 5, sugar: 2, netCarbs: 3, protein: 2, fat: 2 },
    diabetesInfo: { glycemicIndex: 45, glycemicLoad: 1, carbQuality: 'Excellent' },
    allergens: { contains: ['Tree nuts'], mayContain: [], processedIn: [] },
    ingredients: ['Organic coconut'],
  },

  // SNACKS & MISC (10 products)
  {
    upc: '073416000025',
    name: 'Hummus Classic',
    brand: 'Sabra',
    category: 'Dips & Spreads',
    nutrition: { servingSize: '2 tbsp', calories: 70, totalCarbs: 5, fiber: 1, sugar: 0, netCarbs: 4, protein: 2, fat: 5 },
    diabetesInfo: { glycemicIndex: 6, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: ['Sesame'], mayContain: [], processedIn: [] },
    ingredients: ['Cooked chickpeas', 'Tahini', 'Soybean oil', 'Garlic', 'Salt'],
  },
  {
    upc: '041303002377',
    name: 'Dark Chocolate 85%',
    brand: 'Lindt',
    category: 'Snacks',
    nutrition: { servingSize: '4 squares', calories: 230, totalCarbs: 13, fiber: 5, sugar: 4, netCarbs: 8, protein: 4, fat: 20 },
    diabetesInfo: { glycemicIndex: 20, glycemicLoad: 2, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: ['Milk', 'Tree nuts'], processedIn: [] },
    ingredients: ['Chocolate', 'Cocoa butter', 'Cocoa powder', 'Sugar', 'Vanilla'],
  },
  {
    upc: '085239012000',
    name: 'Extra Virgin Olive Oil',
    brand: 'California Olive Ranch',
    category: 'Oils & Vinegar',
    nutrition: { servingSize: '1 tbsp', calories: 120, totalCarbs: 0, fiber: 0, sugar: 0, netCarbs: 0, protein: 0, fat: 14 },
    diabetesInfo: { glycemicIndex: 0, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: [], mayContain: [], processedIn: [] },
    ingredients: ['Extra virgin olive oil'],
  },
  {
    upc: '085239000015',
    name: 'Coconut Oil',
    brand: 'Nutiva',
    category: 'Oils & Vinegar',
    nutrition: { servingSize: '1 tbsp', calories: 120, totalCarbs: 0, fiber: 0, sugar: 0, netCarbs: 0, protein: 0, fat: 14 },
    diabetesInfo: { glycemicIndex: 0, glycemicLoad: 0, carbQuality: 'Excellent' },
    allergens: { contains: ['Tree nuts'], mayContain: [], processedIn: [] },
    ingredients: ['Organic virgin coconut oil'],
  },
]

async function seedExpandedProducts() {
  try {
    await mongoose.connect(process.env.MONGODB_URI)
    console.log('Connected to MongoDB')

    // Don't clear existing products, just add new ones
    const existingUPCs = new Set((await Product.find({}, 'upc')).map(p => p.upc))
    const newProducts = expandedProducts.filter(p => !existingUPCs.has(p.upc))

    if (newProducts.length === 0) {
      console.log('All products already exist in database')
    } else {
      const result = await Product.insertMany(newProducts)
      console.log(`✅ Added ${result.length} new products`)
    }

    // Show total count
    const totalProducts = await Product.countDocuments()
    console.log(`📦 Total products in database: ${totalProducts}`)

    await mongoose.connection.close()
    console.log('Connection closed')
  } catch (error) {
    console.error('Error seeding products:', error)
    process.exit(1)
  }
}

if (require.main === module) {
  seedExpandedProducts()
}

module.exports = seedExpandedProducts
